config/routes.rb
Rails.application.routes.draw do

  root 'quizzes#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  patch 'confirmations/email', to: 'confirmations#email', as: :confirmation_email
  get 'user/quizzes', to: 'users#quizzes', as: 'quizzes_user'

  resources :quizzes do
    resources :questions, shallow: true do
      resources :answers, only: [:update, :destroy]
    end
    resources :quiz_apps, shallow: true do
      get :vkontakte, on: :collection
    end
    resources :points, shallow: true
    get :ratings, on: :member
    get :statistics, on: :member
  end

  resource :game do
    member do
      post :start
      post :check_answer
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  TEMPORARY_EMAIL_PREFIX = 'temporary@email'.freeze
  TEMPORARY_EMAIL_REGEX = /\Atemporary@email/
  TEMPORARY_NAME = 'user_temporary'.freeze

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:facebook, :vkontakte]

  has_many :quizzes, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :games, dependent: :destroy
  has_many :authorizations, dependent: :destroy

  validates :name, presence: true

  def self.find_for_oauth(auth, guest = false)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    return authorization.user if authorization

    email = auth.info[:email] if auth.info && auth.info[:email]
    email ||= "#{TEMPORARY_EMAIL_PREFIX}-#{auth.provider}-#{auth.uid}.com"

    user = User.where(email: email).first
    unless user
      username = "#{TEMPORARY_NAME}-#{auth.provider}-#{auth.uid}"
      password = Devise.friendly_token[0, 20]
      user = User.new(name: username, email: email, password: password, password_confirmation: password)
      user.skip_confirmation_notification! if !guest && user.email_temporary?
      user.skip_confirmation! if guest
      user.save!
    end
    user.create_authorization(auth)
    user
  end

  def create_authorization(auth)
    authorizations.create(provider: auth.provider, uid: auth.uid)
  end

  def email_temporary?
    email && email =~ TEMPORARY_EMAIL_REGEX
  end

  def author?(entity)
    id == entity.user_id
  end

  def place_in(quiz)
    max_score = ratings.find_by(quiz_id: quiz.id).try(:max_score)
    1 + Rating.where(quiz_id: quiz).where('max_score > :max_score', max_score: max_score).count
  end

  def member_quizzes
    ratings.includes(:quiz).map(&:quiz)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def quizzes
    @user_quizzes = current_user.quizzes
    @member_quizzes = current_user.member_quizzes
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/quizzes.html.slim
h2
  | My Quizzes
table.table.table-bordered
  thead
    tr
      th
        | Quiz
      th
        | Users
      th
        | Games
      th
        | Actions
  tbody
    - @user_quizzes.each do |quiz|
      tr
        td
          = link_to quiz.title, quiz_path(quiz)
        td
          = quiz.count_players
        td
          = quiz.count_games
        td
          = link_to 'edit', edit_quiz_path(quiz), class: 'text-success btn'
          = link_to 'statistics', statistics_quiz_path(quiz), class: 'text-success btn'
          = link_to 'ratings', ratings_quiz_path(quiz), class: 'text-success btn'

h2
  | Member of quizzes
table.table.table-bordered
  thead
    tr
      th
        | Quiz
      th
        | Place
      th
        | Ratings
  tbody
    - @member_quizzes.each do |quiz|
      tr
        td
          = link_to quiz.title, quiz_path(quiz)
        td
          = current_user.place_in(quiz)
        td
          = link_to 'ratings', ratings_quiz_path(quiz), class: 'text-success btn'