config/routes.rb
Rails.application.routes.draw do

  root 'quizzes#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  patch 'confirmations/email', to: 'confirmations#email', as: :confirmation_email
  get 'user/quizzes', to: 'users#quizzes', as: 'quizzes_user'

  resources :quizzes do
    resources :questions, shallow: true do
      resources :answers, only: [:update, :destroy]
    end
    resources :quiz_apps, shallow: true do
      get :vkontakte, on: :collection
    end
    resources :points, shallow: true
    get :ratings, on: :member
    get :statistics, on: :member
  end

  resource :game do
    member do
      post :start
      post :check_answer
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user
    if user
      user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
  end

  def user_abilities
    guest_abilities
    can :create, Quiz
    can [:edit, :update, :destroy, :statistics], Quiz, user_id: user.id
    can [:create, :update, :destroy], Question do |question|
      user.author?(question.quiz)
    end
    can [:create, :update, :destroy], Answer do |answer|
      user.author?(answer.question.quiz)
    end
    can [:create, :update, :destroy], QuizApp do |quiz_app|
      user.author?(quiz_app.quiz)
    end
    can [:create, :update, :destroy], Point do |point|
      user.author?(point.quiz)
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
  has_many :questions_games
  has_many :questions, through: :questions_games

  paginates_per 25

  scope :training, -> { joins(:quiz).where('quizzes.once_per > 0').order(:created_at) }
  scope :for_quizzes, ->(_quizzes) { joins(:quiz).where(quiz: _quizzes) }

  def choose_question
    unanswered_questions = quiz.questions.where.not(id: questions)
    return unanswered_questions.first unless quiz.question_randomly
    unanswered_questions.shuffle.sample
  end
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :quiz

  validates :time, :score, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true
  validate :must_be_correct_answer

  private

  def must_be_correct_answer
    errors.add(:base, 'No answer is correct') unless answers.empty? || answers.map(&:correct).include?(true)
  end
end

app/models/questions_game.rb
class QuestionsGame < ApplicationRecord
  belongs_to :game
  belongs_to :question
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :quiz_apps, dependent: :destroy
  has_many :points, dependent: :destroy

  validates :title, :description, :rules, presence: true

  def count_players
    ratings.count(:user_id)
  end

  def count_games
    ratings.sum(:count_games)
  end
end

app/models/quiz_app.rb
class QuizApp < ApplicationRecord
  PLATFORMS = {
    vkontakte: 'vkontakte'
  }.freeze

  belongs_to :quiz

  validates :platform, :app_id, :app_secret, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :quiz

  paginates_per 20

  scope :first_max_score, -> { order('max_score DESC') }
end

app/models/user.rb
class User < ApplicationRecord
  TEMPORARY_EMAIL_PREFIX = 'temporary@email'.freeze
  TEMPORARY_EMAIL_REGEX = /\Atemporary@email/
  TEMPORARY_NAME = 'user_temporary'.freeze

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:facebook, :vkontakte]

  has_many :quizzes, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :games, dependent: :destroy
  has_many :authorizations, dependent: :destroy

  validates :name, presence: true

  def self.find_for_oauth(auth, guest = false)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    return authorization.user if authorization

    email = auth.info[:email] if auth.info && auth.info[:email]
    email ||= "#{TEMPORARY_EMAIL_PREFIX}-#{auth.provider}-#{auth.uid}.com"

    user = User.where(email: email).first
    unless user
      username = "#{TEMPORARY_NAME}-#{auth.provider}-#{auth.uid}"
      password = Devise.friendly_token[0, 20]
      user = User.new(name: username, email: email, password: password, password_confirmation: password)
      user.skip_confirmation_notification! if !guest && user.email_temporary?
      user.skip_confirmation! if guest
      user.save!
    end
    user.create_authorization(auth)
    user
  end

  def create_authorization(auth)
    authorizations.create(provider: auth.provider, uid: auth.uid)
  end

  def email_temporary?
    email && email =~ TEMPORARY_EMAIL_REGEX
  end

  def author?(entity)
    id == entity.user_id
  end

  def place_in(quiz)
    max_score = ratings.find_by(quiz_id: quiz.id).try(:max_score)
    1 + Rating.where(quiz_id: quiz).where('max_score > :max_score', max_score: max_score).count
  end

  def member_quizzes
    ratings.includes(:quiz).map(&:quiz)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_apps_helper.rb
module QuizAppsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/iframe.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @quiz.title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'play-quiz' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.slim
nav class="navbar  navbar-default navbar-fixed-top"
  .container
    .navbar-header
      a class="navbar-brand" href="#"
        | Project name
    div id="navbar" class="collapse navbar-collapse"
      ul class="nav navbar-nav"
        li
          = link_to 'Home', root_path
        - if user_signed_in?
          li
            = link_to 'Create Quiz',  new_quiz_path
          li
            = link_to 'My quizzes', quizzes_user_path
      ul class="nav navbar-nav navbar-right"
        - if user_signed_in?
            li
              = link_to "Hello, #{current_user.name}", '#'
            li
              = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
            li
               = link_to 'Sign in', new_user_session_path
            li
              = link_to 'Sign up', new_user_registration_path